### ISSUE TITLE
XmlPullParserException

### ISSUE THREAD

**Issue by ViliusSutkus89** [ViliusSutkus89/Fontconfig-Android-translator#37]
https://github.com/ViliusSutkus89/pdf2htmlEX-Android/issues/83

```
W/System.err: org.xmlpull.v1.XmlPullParserException: expected: END_TAG {null}family (position:END_TAG </axis tag='ital' stylevalue='0'>@28:45 in java.io.InputStreamReader@80377c5) 
W/System.err:     at com.android.org.kxml2.io.KXmlParser.require(KXmlParser.java:2067)
W/System.err:     at com.viliussutkus89.android.fontconfigtranslator.FontconfigTranslator$FontFamily.<init>(FontconfigTranslator.java:245)
W/System.err:     at com.viliussutkus89.android.fontconfigtranslator.FontconfigTranslator.translate(FontconfigTranslator.java:104)
W/System.err:     at com.viliussutkus89.android.pdf2htmlex.FontconfigAndroid.init(FontconfigAndroid.java:27)
W/System.err:     at com.viliussutkus89.android.pdf2htmlex.pdf2htmlEX.<init>(pdf2htmlEX.java:119)
```

**Comment by ViliusSutkus89** [comment]
[fonts.xml.txt](https://github.com/ViliusSutkus89/Fontconfig-Android-translator/files/13786759/fonts.xml.txt)
